### ISSUE TITLE
No such key in schema

### ISSUE THREAD

**Issue by Zoibderg** [elementary/switchboard#141]
## Prerequisites
- [X] I have searched open and closed issues for duplicates.

## Describe the bug
I'm running into an error when trying to install Switchboard on elementary OS. Everything seems to be going fine until the install process gets to Compiling gsettings schemas... 

Once I get to that point I get these 2 errors - 

No such key 'button-layout' in schema 'org.gnome.mutter:Pantheon' as specified in override file '/usr/share/glib-2.0/schemas/20_elementary.pantheon.wm.gschema.override'; ignoring override for this key.

No such key 'enable-animations' in schema 'org.gnome.mutter:Pantheon' as specified in override file '/usr/share/glib-2.0/schemas/20_elementary.pantheon.wm.gschema.override'; ignoring override for this key.

### Screenshots or screen recordings
![Screenshot from 2020-02-13 18 04 18](https://user-images.githubusercontent.com/43228316/74492913-b8712700-4e8d-11ea-93ab-c1f32ad51a0b.png)

## Platform Information
![Screenshot from 2020-02-13 18 17 17](https://user-images.githubusercontent.com/43228316/74492929-c32bbc00-4e8d-11ea-8be1-d3ff87c4a0d1.png)

- [X] I'm using the latest version from git that I've manually compiled
- [X] I'm using the latest released stable version

## Additional context

I thought this might have something to do with dependencies, but have not been able to solve the issue. I've tried installing all dependencies one by one, updating them, upgrading them and also sudo apt -f install to try and fix and errors. 

I'm mainly trying to get Switchboard installed so that I can use the switchboard plug keyboard lock indicators. https://github.com/elementary/switchboard-plug-keyboard

If anyone can help me out with this it would be greatly appreciated!

**Comment by donadigo** [comment]
These are not critical errors. They are warnings you can ignore, and you should just try to test the compiled version. The command for switchboard is `io.elementary.switchboard`.

The warnings come from the other component which is gala/mutter, which you still can ignore, even if you're compiling them too.

**Comment by donadigo** [comment]
Furthermore, if you just want the stable version you can install `sudo apt install switchboard switchboard-plug-*`. That will install Switchboard and all the settings.

**Comment by Zoibderg** [comment]
Awesome! That worked wonderfully, the only issue now is that when I'm in switchboard, I'm still not getting the keyboard options. I'm sure its just something I'm not fully understanding again, I'm pretty new to Linux, so this is all different for me.
![Screenshot from 2020-02-13 21 32 01](https://user-images.githubusercontent.com/43228316/74501744-4d811980-4ea8-11ea-961d-8b7fe3f8db2d.png)
I'm expecting to see the option to show the num and caps lock in the panel here.
I've double check and reinstalled switchboard-keyboard with the sudo apt install switchboard switchboard-plug-keyboard, but honestly, I'm not sure if I'm even doing that right.
