### ISSUE TITLE
No color setting in system setting? how loading my monitor icc profile?

### ISSUE THREAD

**Issue by windfromdesert** [elementary/switchboard#143]
## Prerequisites
- [ ] I have searched open and closed issues for duplicates.

## Feature
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Existing work**

**Describe alternatives you've considered**

**Additional context**

**Comment by danrabbit** [comment]
closing as a duplicate of https://github.com/elementary/switchboard-plug-display/issues/5
