### ISSUE TITLE
Switchboard translation error. Portuguese(pt)

### ISSUE THREAD

**Issue by hugok79** [elementary/switchboard#144]
There is a typo in switchboard.
 In (All Settings) appear Wacom Settings....
The screenshot bellow show that... but in (portuguese)

[Captura de ecrã de 2020-03-24 14 27 47](https://user-images.githubusercontent.com/16929048/77437350-761bfd80-6ddc-11ea-9c0f-b86b20e0233d.png)

**Comment by tintou** [comment]
Were you previously in the Wacom Setttings pane ? because if so that button is here to return there :)

**Comment by hugok79** [comment]
I don't have any wacom device...

**Comment by hugok79** [comment]
It was a recent update that changed that

**Comment by tintou** [comment]
Ah indeed, this has been fixed already in master https://github.com/elementary/switchboard/commit/d24c0bf3ccdc289b2de32779742ae03fcef458cb we just need another release

**Comment by hugok79** [comment]
Ok thanks!! Every switch plug that I select shows "Wacom Settings" instead of "All Settings"
I've check all .po files in elementary weblate and everything is well translated.
So I have to wait for a new update, right?

**Comment by tintou** [comment]
Exactly, it should be fixed in next update

**Comment by hugok79** [comment]
Thanks for your help @tintou 
I always try to keep the Portuguese(pt) well translated and 100% completed.
