### ISSUE TITLE
Add margin between labels and icons

### ISSUE THREAD

**Issue by ghost** [elementary/switchboard#154]
There is no gap set between labels and the icons on System Settings. Although it looks like there is, it's actually the line-height of the label.

![Captura de tela de 2020-04-26 23-53-28](https://user-images.githubusercontent.com/24512504/80380090-72fdac80-8875-11ea-8ee8-e15f636de34b.png)
![Captura de tela de 2020-04-26 23-54-39](https://user-images.githubusercontent.com/24512504/80380108-7abd5100-8875-11ea-8991-f0d93b4a53a0.png)

This is how it looks right now:

![Captura de tela de 2020-04-27 00-05-30](https://user-images.githubusercontent.com/24512504/80380188-97f21f80-8875-11ea-92c7-4bdce588b7cd.png)

I suggest adding a gap between then to increase legibility. Something like this:

![Captura de tela de 2020-04-27 00-05-48](https://user-images.githubusercontent.com/24512504/80380212-a04a5a80-8875-11ea-9fb3-9261331d9817.png)

**Comment by danirabbit** [comment]
Closing as fixed by #233
