### ISSUE TITLE
Plugs are missing

### ISSUE THREAD

**Issue by SolarAquarion** [elementary/switchboard#169]
switchboard-git r1427.c27d957-1

![screengrab-2020-05-22-18-32-46](https://user-images.githubusercontent.com/5307016/82714103-3f872580-9c5b-11ea-86b8-cf167acc0520.png)

**Comment by ryonakano** [comment]
It should not happen in fresh elementary OS. Are you happen to install Switchboard on another distro?

**Comment by SolarAquarion** [comment]
Yes, Arch Linux

**Comment by ryonakano** [comment]
Did you installed AURs of Plugs correctlly?

**Comment by SolarAquarion** [comment]
Yes, I think I did. Unless you want me to strace or similar em.

**Comment by danrabbit** [comment]
Switchboard itself is an empty container. You need to install the individual extensions for each settings pane

**Comment by SolarAquarion** [comment]
@danrabbit for some reason I can't interact with the search stuff of switchboard.

**Comment by SolarAquarion** [comment]
@ryonakano yeah, for some reason, the only thing I can do, is close the window.  I can't search or do other things that the empty container has.

**Comment by SolarAquarion** [comment]
I got a stack trace

> 
>       Stack trace of thread 180407:
>                 #0  0x00007fe182cab083 g_logv (libglib-2.0.so.0 + 0x5b083)
>                 #1  0x00007fe182cab300 g_log (libglib-2.0.so.0 + 0x5b300)
>                 #2  0x00007fe181972666 n/a (libatk-bridge-2.0.so.0 + 0xc666)
>                 #3  0x00007fe181208e01 dbus_connection_dispatch (libdbus-1.so.3 + 0x15e01)
>                 #4  0x00007fe1811cceb7 n/a (libatspi.so.0 + 0x10eb7)
>                 #5  0x00007fe182ca2914 g_main_context_dispatch (libglib-2.0.so.0 + 0x52914)
>                 #6  0x00007fe182cf67d1 n/a (libglib-2.0.so.0 + 0xa67d1)
>                 #7  0x00007fe182ca1e63 g_main_loop_run (libglib-2.0.so.0 + 0x51e63)
>                 #8  0x00007fe1823f1e4f gtk_main (libgtk-3.so.0 + 0x24fe4f)
>                 #9  0x000055a6b970e8a9 n/a (io.elementary.switchboard + 0xd8a9)
>                 #10 0x00007fe182a6b98a g_signal_emit_valist (libgobject-2.0.so.0 + 0x2f98a)
>                 #11 0x00007fe182a6bb00 g_signal_emit (libgobject-2.0.so.0 + 0x2fb00)
>                 #12 0x00007fe182b60b09 n/a (libgio-2.0.so.0 + 0xccb09)
>                 #13 0x00007fe182b60c8a g_application_run (libgio-2.0.so.0 + 0xccc8a)
>                 #14 0x000055a6b970c320 switchboard_main (io.elementary.switchboard + 0xb320)
>                 #15 0x00007fe181efa152 __libc_start_main (libc.so.6 + 0x28152)
>                 #16 0x000055a6b970805e _start (io.elementary.switchboard + 0x705e)
>                 
>                 Stack trace of thread 180408:
>                 #0  0x00007fe181fc746f __poll (libc.so.6 + 0xf546f)
>                 #1  0x00007fe182cf675f n/a (libglib-2.0.so.0 + 0xa675f)
>                 #2  0x00007fe182ca1121 g_main_context_iteration (libglib-2.0.so.0 + 0x51121)
>                 #3  0x00007fe182ca1172 n/a (libglib-2.0.so.0 + 0x51172)
>                 #4  0x00007fe182ccfce1 n/a (libglib-2.0.so.0 + 0x7fce1)
>                 #5  0x00007fe181e423e9 start_thread (libpthread.so.0 + 0x93e9)
>                 #6  0x00007fe181fd2293 __clone (libc.so.6 + 0x100293)
>                 
>                 Stack trace of thread 180409:
>                 #0  0x00007fe181fc746f __poll (libc.so.6 + 0xf546f)
>                 #1  0x00007fe182cf675f n/a (libglib-2.0.so.0 + 0xa675f)
>                 #2  0x00007fe182ca1e63 g_main_loop_run (libglib-2.0.so.0 + 0x51e63)
>                 #3  0x00007fe182b95fe8 n/a (libgio-2.0.so.0 + 0x101fe8)
>                 #4  0x00007fe182ccfce1 n/a (libglib-2.0.so.0 + 0x7fce1)
>                 #5  0x00007fe181e423e9 start_thread (libpthread.so.0 + 0x93e9)
>                 #6  0x00007fe181fd2293 __clone (libc.so.6 + 0x100293)
>                 
>                 Stack trace of thread 180410:
>                 #0  0x00007fe181fc746f __poll (libc.so.6 + 0xf546f)
>                 #1  0x00007fe182cf675f n/a (libglib-2.0.so.0 + 0xa675f)
>                 #2  0x00007fe182ca1121 g_main_context_iteration (libglib-2.0.so.0 + 0x51121)
>                 #3  0x00007fe180080c0e n/a (libdconfsettings.so + 0x5c0e)
>                 #4  0x00007fe182ccfce1 n/a (libglib-2.0.so.0 + 0x7fce1)
>                 #5  0x00007fe181e423e9 start_thread (libpthread.so.0 + 0x93e9)
>                 #6  0x00007fe181fd2293 __clone (libc.so.6 + 0x100293)
>                 
>                 Stack trace of thread 180411:
>                 #0  0x00007fe181fccd5d syscall (libc.so.6 + 0xfad5d)
>                 #1  0x00007fe182cef8bb g_cond_wait_until (libglib-2.0.so.0 + 0x9f8bb)
>                 #2  0x00007fe182c72813 n/a (libglib-2.0.so.0 + 0x22813)
>                 #3  0x00007fe182cd2ceb n/a (libglib-2.0.so.0 + 0x82ceb)
>                 #4  0x00007fe182ccfce1 n/a (libglib-2.0.so.0 + 0x7fce1)
>                 #5  0x00007fe181e423e9 start_thread (libpthread.so.0 + 0x93e9)
>                 #6  0x00007fe181fd2293 __clone (libc.so.6 + 0x100293)

**Comment by cassidyjames** [comment]
@SolarAquarion Switchboard **has no functionality on its own.** You need to install [plugs](https://github.com/elementary?q=switchboard-plug#org-repositories) from source or your package manager for anything to show up and work in Switchboard. Once there are some plugs installed externally, opening Switchboard will show those plugs and allow searching through the installed plugs.

**Comment by SolarAquarion** [comment]
I've installed and rebuilt all the plugs, so either.  So either something
is going on with all the plugs, or something is going on with Switchboard.
If all plugs are installed correctly. and properly linked, then the only
thing i can blame is Switchboard. No?
