### ISSUE TITLE
libhandy-1-0 (>= 0.80.0) but it is not installable

### ISSUE THREAD

**Issue by sergiojod** [elementary/switchboard#173]
## Prerequisites
- [ ] I have searched open and closed issues for duplicates.

## Describe the bug

If applicable, add screenshots or screen recordings to help explain your problem.

## Platform Information

- [ ] I'm using the latest version from git that I've manually compiled
- [ ] I'm using the latest released stable version

**Comment by danrabbit** [comment]
This is not a valid issue report. Please actually fill out the issue template in the future.
