### ISSUE TITLE
The interface doesn't fit on the screen

### ISSUE THREAD

**Issue by thirdsty** [elementary/switchboard#176]
### After installing elementary-tweaks, the settings do not fit on the screen.
Screen resolution 1366x768.

![Image alt](https://i.ibb.co/ygMxLZM/2020-06-20-10-56-45.png)
(if the image didn't load - https://i.ibb.co/ygMxLZM/2020-06-20-10-56-45.png)

**Comment by gavnokysok** [comment]
такая же проблема

**Comment by DanilChechkov** [comment]
So what do I have to do and how can I add this scroll?
