### ISSUE TITLE
Search returns alphabetically sorted list after clicking on a search result

### ISSUE THREAD

**Issue by vikasnataraja** [elementary/switchboard#182]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug

After typing something in the search bar and clicking on a search result, an alphabetically sorted list appears for a split second before resuming with the click action

### To Reproduce
1. Go to System Settings
2. Type something and click on a search result
3. See bug

### Expected behavior
The click should be instantaneous and the action of the click should follow without that list.

### Screenshots or screen recordings

![system-settings](https://user-images.githubusercontent.com/46734097/86869541-fcaad100-c093-11ea-93c6-189916d2e2d9.gif)

## Platform Information

![image](https://user-images.githubusercontent.com/46734097/86868499-0d5a4780-c092-11ea-8be3-26ae2851b103.png)

Please check what applies:
-->
- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

## Additional context
I reinstalled elementaryOS today after an OS wipe and just noticed this error. I was on Hera 5.1.4 earlier and this error wasn't occurring back then. Of course, I was using kernel 5.3.0-37-generic earlier and now it is 5.3.0-62-generic.

**Comment by alainm23** [comment]
I don't consider it a bug, just a design detail.
