### ISSUE TITLE
Thunderbolt Security Settings

### ISSUE THREAD

**Issue by ryanfelder** [elementary/switchboard#193]
I'm participating in the Elementary OS 6 beta. I run a Lenovo Yoga 920 as my primary.

I installed Odin, but none of my devices that I connect via Thunderbolt were working except my external monitor.
No keyboard, no ethernet, no sound, etc. I did my normal troubleshooting, installed firmware, upgraded the kernel, no luck.
I just assumed something was off about the beta and went back to Elementary OS 5.

That was, up until a few days ago when I needed glibc 2.29 for something and decided to give Odin another shot. 
When I rebooted from 5 to 6, amazingly all my devices worked... until I disconnected and reconnected the Thunderbolt.
That's when I remembered there's a security setting I needed in udev before my thunderbolt devices would be trusted.

I found the setting I needed on the arch wiki, and suddenly everything worked again. I now use Odin as my daily driver.

This was not an intuitive experience. I thought Odin was broken for months and I consider myself fairly savvy with Linux, having run it as my daily for 10+ years. 

I would like to suggest that a notification come up when I connect a Thunderbolt device that isn't trusted, and expose the settings for trusting Thunderbolt devices somewhere in switchboard. If there is already support for trusting Thunderbolt devices in the UI somewhere, I still haven't been able to find it.

**Comment by meisenzahl** [comment]
Hey @ryanfelder could you provide a link to the article in the Arch Wiki and the udev rule you added.

**Comment by ryanfelder** [comment]
https://wiki.archlinux.org/index.php/Thunderbolt

Specifically, I followed the procedure documented here...

```
Automatically connect any device
Users who just want to connect any device without any sort of manual work can create a udev rule as in 99-removable.rules:

/etc/udev/rules.d/99-removable.rules
ACTION=="add", SUBSYSTEM=="thunderbolt", ATTR{authorized}=="0", ATTR{authorized}="1"
```

Apparently Gnome has UI support for this already...
https://wiki.gnome.org/Design/Whiteboards/ThunderboltAccess

I only did this procedure once before when I got the laptop so I had completely forgotten it was necessary by the time I installed Odin.

**Comment by danrabbit** [comment]
Hey thanks for reporting this. Thunderbolt settings are already being tracked here: https://github.com/elementary/switchboard-plug-security-privacy/issues/108

Closing as a duplicate
