### ISSUE TITLE
Headerbar height is not preserved throughout

### ISSUE THREAD

**Issue by hanaral** [elementary/switchboard#200]
## What Happened
The height of the app headerbar jumps based on the plug, especially on CJK system locales. 
I quote Daniel; _"It looks like the problem is using hide () and show () doesn't preserve space in the navigation_button. This should probably use a Gtk.Revealer instead"_

## Expected Behavior

The headerbar height remains consistent

## Steps to Reproduce

Navigate plugs in the app

## Platform Information
elementary OS 6 Odin

**Comment by danrabbit** [comment]
So it seems adding a revealer here clips box shadow which is annoying. An alternative would be doing something like Onboarding where we're syncing opacity values to the page swipe and then we can set sensitivity after the transition finishes

**Comment by danirabbit** [comment]
This is technically fixed in that panes now draw their own window controls. The grabbable area is different in different panes based on header height, but this is largely invisible. There's no longer a single header that has its contents changing so :shrug: closing since it's no longer applicable
