### ISSUE TITLE
New Gestures Can Become Stuck!

### ISSUE THREAD

**Issue by TobyMaddix** [elementary/switchboard#208]
## What Happened
When using a scroll gesture, the panel can sometimes become stuck!
![image](https://user-images.githubusercontent.com/25801673/117818750-6e295200-b258-11eb-8d2a-6532e4efa918.png)
Clicking an option while using the gesture can reproduce this.

## Expected Behavior
It should just slide away as normal.

## Steps to Reproduce
1. Start to go back to the panel using the gesture
2. Click an option at the same time
3. Should become stuck

## Platform Information
6.0 beta

**Comment by danirabbit** [comment]
Gestures are handled by a library, so if this is a reproducible issue it needs to be reporting to LibAdwaita. Closing as "Out of scope"
