### ISSUE TITLE
[new plug] a developer panel to change dconf settings

### ISSUE THREAD

**Issue by hanaral** [elementary/switchboard#210]
## Problem

Not too much of a problem but I think it's odd to have to install a non-elementary app for managing dconf settings

## Proposal

Offer a developer plug that reveals itself under certain criteria (I have no clue what it could be) containing a panel for managing dconf settings that could help with app testing (maybe restrict it just to stuff under com/github/)
This seems like an ambitious proposal and I could get not wanting to in fear that people will Android style find ways to enable it and mess with stuff they aren't supposed to

**Comment by jeremypw** [comment]
I doubt giving elementary blessing to the user to mess carte blanche with the settings will get much traction.  I long ago considered making a plug to change e.g. Files settings like single-click/double-click that (were) supported but not exposed in the Files UI but again no traction. I guess if something is intended to be changed then it should be exposed in the app UI.

**Comment by hanaral** [comment]
This is specifically for development, but I suppose it should have its own app like dconf editor

**Comment by Marukesu** [comment]
Sandboxed Apps do not use DConf as backend  anyway, instead they use a keyfile inside the sandbox. We can't edit or read them from the host.
