### ISSUE TITLE
Some comboboxes are longer than necessary

### ISSUE THREAD

**Issue by D0J0P** [elementary/switchboard#219]
### What Happened?

There are some settings where the combobox are a lot longer than they could be. Some take up the entire width of the window and if you click on them, you'll see the selection that has the most letters doesn't need that wide of a combobox.

This happen in Sharing, Network, Power and Mouse & Touchpad.

### Steps to Reproduce

![Screenshot from 2021-10-01 13 28 39](https://user-images.githubusercontent.com/19495660/136868866-a3b53d72-ccfe-49a1-9c4a-e06ca72b477c.png)
![Screenshot from 2021-10-01 13 28 59](https://user-images.githubusercontent.com/19495660/136868875-c86593fc-b85c-4ff4-828a-df890bc1abe1.png)
![Screenshot from 2021-10-01 13 30 15](https://user-images.githubusercontent.com/19495660/136869046-c7137b46-2b7c-458d-8c4d-a6ee09db174f.png)
![Screenshot from 2021-10-01 13 30 34](https://user-images.githubusercontent.com/19495660/136869052-376ff0f2-3a67-4373-bc8f-29822329025e.png)

### Expected Behavior

That the padding wouldn't be longer than needed.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by danirabbit** [comment]
Now that we have clamps in the SettingsPage I think this is as fixed as Settings itself can make it. Individual views will have to provide their own clamps if they don't use SettingsPage
