### ISSUE TITLE
Port System Settings to GTK4

### ISSUE THREAD

**Issue by danrabbit** [elementary/switchboard#224]

**Comment by davidmhewitt** [comment]
Similar to https://github.com/elementary/wingpanel/issues/426 , this is probably reasonably important to get done in time for the OS 7 release as all the plugs will have to be ported and released at once.

Probably less risky (in terms of not completely breaking the shell) to release this during the cycle, but still quite high impact.

**Comment by danrabbit** [comment]
I'm wondering if it makes more sense to punt this to OS 8 since it will be such a huge project. This might also be a good time for a redesign if we want to consider responsive/mobile cases

**Comment by danrabbit** [comment]
Gonna go ahead and close this since the `main` branch exists and can be installed alongside gtk3 switchboard
