### ISSUE TITLE
Port plugs to GTK4

### ISSUE THREAD

**Issue by leolost2605** [elementary/switchboard#267]
Might be good to have a little overview of GTK4 switchboard progress:

- [x] [Online Accounts](https://github.com/elementary/switchboard-plug-onlineaccounts)
- [x] [Pantheon Shell](https://github.com/elementary/switchboard-plug-pantheon-shell)
- [x] [Sound](https://github.com/elementary/switchboard-plug-sound)
- [x] [Privacy](https://github.com/elementary/switchboard-plug-security-privacy)
- [x] [Keyboard](https://github.com/elementary/switchboard-plug-keyboard)
- [x] [Wacom](https://github.com/elementary/switchboard-plug-wacom)
- [x] [Display](https://github.com/elementary/switchboard-plug-display)
- [x] [Network](https://github.com/elementary/switchboard-plug-network)
- [x] [Applications](https://github.com/elementary/switchboard-plug-applications) (Needs update)
- [x] [Parental Controls](https://github.com/elementary/switchboard-plug-parental-controls)
- [x] [Notifications](https://github.com/elementary/switchboard-plug-notifications)
- [x] [A11y](https://github.com/elementary/switchboard-plug-a11y)
- [x] [About](https://github.com/elementary/switchboard-plug-about)
- [x] [User Accounts](https://github.com/elementary/switchboard-plug-useraccounts)
- [x] [Power](https://github.com/elementary/switchboard-plug-power)
- [x] [Locale](https://github.com/elementary/switchboard-plug-locale)
- [x] [Printers](https://github.com/elementary/switchboard-plug-printers)
- [x] [Mouse Touchpad](https://github.com/elementary/switchboard-plug-mouse-touchpad)
- [x] [Datetime](https://github.com/elementary/switchboard-plug-datetime) (Needs update)
- [x] [Bluetooth](https://github.com/elementary/switchboard-plug-bluetooth)
- [x] [Sharing](https://github.com/elementary/switchboard-plug-sharing)

**Comment by lenemter** [comment]
Wacom port was merged so this is fixed now :tada:
