### ISSUE TITLE
[eOS 8.0 daily build 20240217] Plank dock does not automatically start on login to X.Org Session

### ISSUE THREAD

**Issue by truefakts** [elementary/switchboard#297]
### What Happened?

**NOTE:** This probably isn't the right issue board to log this bug. But if I click the "Dock" from the desktop components field in the feedback app, it does nothing. Presumably it would link me to https://github.com/ricotz/plank to report an issue with Plank. However I don't think this is a Plank issue, so I'm putting this bug report here. Please move this issue if it's in the wrong spot

**NOTE 2:** Full disclosure, I'm running this in a VM. But I doubt that is related to this.

I encountered an issue upon login while using the early access build of Elementary OS 8.0, specifically the iso from 20240217. Upon login to the default X.org session, Plank is not running, thus there is no dock. Plank can be manually started from the app menu, and it works without issue. If you manually add it to the startup applications list, it works without issue. I suspect the root cause is that this application isn't set to run on startup, and not actually an issue with Plank.

Below is a screenshot of a fresh boot on a fresh install which shows Plank not running, and not present in the Startup Applications list.

![Screenshot from 2024-02-17 16 37 01](https://github.com/elementary/switchboard/assets/47705198/dc31ca3e-28af-418f-90ac-9830474b104b)

### Steps to Reproduce

1. Install the Operating System
2. Login
3. Observe that Plank is not there

### Expected Behavior

1. Install the Operating System
2. Login
3. Plank should be present automatically, without manually invoking the application

### OS Version

Early Access

### Software Version

Latest release (I have run all updates)

### Log Output

```shell
N/A
```

### Hardware Info

Hardware Info

This was tested in a VM using Gnome Boxes in a flatpak

Host machine: (probably irrelevant)

- Linux Mint 21.3 Cinnamon Edition
- Linux drew-desktop 6.7.3-060703-generic #202401311935 SMP PREEMPT_DYNAMIC Thu Feb 1 00:46:47 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
- Ryzen 5 5600X
- RX 6600 XT
- 16GB of RAM

VM running elementary OS

- OS: elementary OS 8 Early Access x86_64
- Host: KVM/QEMU (Standard PC (Q35 + ICH9, 2009) pc-q35-7.2)
- Kernel: 6.6.0-14-generic
- Uptime: 1 min
- Packages: 1736 (dpkg), 17 (flatpak)
- Shell: bash 5.2.21
- Resolution: 2560x1440
- DE: Pantheon
- WM: Mutter(Gala)
- Theme: io.elementary.stylesheet.mint [GTK3]
- Icons: elementary [GTK3]
- Terminal: io.elementary.t
- GPU: 00:01.0 Red Hat, Inc. QXL paravirtual graphic card
- Memory: 981MiB / 3896MiB

**Comment by lenemter** [comment]
This is intended. Plank is no longer developed and a new dock is in development. The reason the new dock is not starting up is [this](https://github.com/elementary/dock/pull/214)
