### ISSUE TITLE
Make 'Back' key go back

### ISSUE THREAD

**Issue by uncertainquark** [elementary/switchboard#33]
Take this mouse settings plus for example. Hitting back button from here doesn't take us back to the main Settings pane.

![screenshot from 2017-05-19 22 08 38](https://cloud.githubusercontent.com/assets/22585732/26257948/1e34a486-3cb2-11e7-89df-d23a22c3bcc6.png)

**Comment by danrabbit** [comment]
Can you elaborate? What happens you click back here? The label "All Settings" indicates that it should take you back to the all settings view

**Comment by uncertainquark** [comment]
Sorry, I meant that when I click the back button on the _keyboard_, on any of the settings plugs, it doesn't take back to the main settings pane.
