### ISSUE TITLE
Search bar is unresponsive when not on the main page.

### ISSUE THREAD

**Issue by winrg** [elementary/switchboard#334]
### What Happened?

When navigated anywhere other than the main page, the search bar is deselected and unusable, but it prompts the user to "search settings". Despite this, clicking he search bar does nothing.

### Steps to Reproduce

Open settings, go anywhere, click on the search bar.

### Expected Behavior

Ideally, clicking it would send the user to the main page. The current flow is unintuitive.

### OS Version

7.x (Horus)

### Session Type

Classic Session (X11, This is the default)

### Software Version

Latest release (I have run all updates)

**Comment by danirabbit** [comment]
This was fixed in OS 8 :)
