### ISSUE TITLE
Sound set to dummy device after suspend (No repository for switchboard-plug-sound?)

### ISSUE THREAD

**Issue by richardwonka** [elementary/switchboard#34]
I'd like to report a bug about sound being routed towards a dummy device after waking up, but I couldn't find the repository switchboard-plug-sound, so I'm reporting here, seems the best choice.

As in the title: When my system wakes up from suspend, sound is routed towards a dummy device and only becomes audible when I re-select local speakers or HDMI/DisplayPort output.

![sound routed to dummy output device - screenshot from 2017-05-23 15 34 46](https://cloud.githubusercontent.com/assets/304005/26345795/3fc655a8-3fce-11e7-8c80-32a1732005c1.png)

**Comment by danrabbit** [comment]
This sounds like probably an issue in PulseAudio, but the repository for the sound plug is [here](https://github.com/elementary/switchboard-plug-sound/issues)

Closing as invalid for Switchboard itself since the issue can't be solved in this codebase

**Comment by grvrulz** [comment]
For reference, the proper issue for this is https://github.com/elementary/switchboard-plug-sound/issues/8
