### ISSUE TITLE
The "Suggest Translation" button is pointing to the wrong link

### ISSUE THREAD

**Issue by GabrielMGitHub** [elementary/switchboard#35]
The "Suggest Translation" button is pointing to the wrong link. This error has several applications.

https://translations.launchpad.net/switchboard
![captura de tela de 2017-05-27 14-40-38](https://cloud.githubusercontent.com/assets/8754997/26523282/9141f512-42ea-11e7-860c-fe5c0a171d97.png)

**Comment by bil-elmoussaoui** [comment]
Already fixed on master 
https://github.com/elementary/switchboard/blob/master/src/Switchboard.vala#L81
