### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by kjlaw89** [elementary/switchboard#37]
I can't open Switchboard anymore. This is a brand new elementary installation that has all of its updates installed and a few apps all from the app store. When I attempt to run Switchboard nothing loads. I tried to run it in the terminal and got:

```
kj@kj-elementary:~$ switchboard

(switchboard:26094): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2045:14: 'min-height' is not a valid property name

(switchboard:26094): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2046:13: 'min-width' is not a valid property name

(switchboard:26094): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2051:13: 'min-width' is not a valid property name
get chip id failed: -1 [13]
param: 4, val: 0
[intel_init_bufmgr:1166] Error initializing buffer manager.

(switchboard:26094): GLib-CRITICAL **: g_strsplit: assertion 'string != NULL' failed
Segmentation fault (core dumped)
```

**Comment by donadigo** [comment]
Are you able to provide an output of debugging that? You can do this by running in your terminal: `gdb switchboard`, after that type `run`, hit enter. Finally type `bt` and hit enter again and paste the output here. This should give as all the needed information.

**Comment by kjlaw89** [comment]
Well, seems to have cleared on its own. Came back after awhile and my computer was sitting at a black screen with a blinking cursor. After I reset my computer I was able to open it up. I had just run some updates so maybe it was just in a bad state...

Thanks for the response!
