### ISSUE TITLE
Switchboard hangs loading switchboard-plug-gcc-sound

### ISSUE THREAD

**Issue by Nine-H** [elementary/switchboard#53]
Reporting here because it's complaining about NMSetting, which I thought was network management.

```
[WARNING 17:34:01.934485] [GLib-GObject] cannot register existing type 'NMSetting'
[FATAL 17:34:01.934518] [GLib] g_once_init_leave: assertion 'result != 0' failed
[FATAL 17:34:01.934542] [GLib-GObject] g_type_register_static: assertion 'parent_type > 0' failed
[FATAL 17:34:01.934566] [libnm-util] _nm_register_setting: assertion 'type != G_TYPE_INVALID' failed
[FATAL 17:34:01.934588] [GLib] g_once_init_leave: assertion 'result != 0' failed
```

**Comment by Janiczek** [comment]
Might have to do with https://github.com/elementary/wingpanel/issues/75#issuecomment-353781679

**Comment by Janiczek** [comment]
Also, the sound doesn't work for me at all. I think it's related. I'll be glad to help debug this.

**Comment by arshubham** [comment]
This happen with all gcc plugs. I can't open wacom, and color too.

**Comment by Fussverkehr** [comment]
I have the same Bug, with switchboard-gcc-plug-sound and switchboard-gcc-plug-color

**Comment by tintou** [comment]
You need to remove them, they are no more compatible with the stack, please use an official ISO if you want a stable system.

**Comment by shishkovoleg** [comment]
Could you explain how to fix sound settings?

**Comment by tintou** [comment]
@shishkovoleg Use the official iso, on the development stack, you don't need GCC plugs anymore as there are native substitutions

**Comment by shishkovoleg** [comment]
It would be nice if you share link for the official iso.

**Comment by tintou** [comment]
@shishkovoleg available since always here https://elementary.io/ ;)

**Comment by shishkovoleg** [comment]
Do you suggest to reinstall whole system using latest Elementary OS release to fix issue with sound settings?

**Comment by tintou** [comment]
You probably have a development version of elementary OS on which packages are unstable, so this is probably the best solution, please use the official stable ISO to install it if you don't want to encounter any issue.
If you've knowledge with APT, you need to remove the elementary daily PPA to come back to stable.

**Comment by arshubham** [comment]
> If you've knowledge with APT, you need to remove the elementary daily PPA to come back to stable.

@shishkovoleg  You have to use ```ppa-purge``` for this. It worked for me, but no guaranties

**Comment by shishkovoleg** [comment]
@tintou @arshubham Thank you very much!

I did the trick with the following commands
`grep ppa /etc/apt/sources.list /etc/apt/sources.list.d/* | grep daily`

/etc/apt/sources.list.d/elementary-os-ubuntu-daily-xenial.list:deb http://ppa.launchpad.net/elementary-os/daily/ubuntu xenial main
/etc/apt/sources.list.d/elementary-os-ubuntu-daily-xenial.list:# deb-src http://ppa.launchpad.net/elementary-os/daily/ubuntu xenial main
/etc/apt/sources.list.d/elementary-os-ubuntu-daily-xenial.list.save:deb http://ppa.launchpad.net/elementary-os/daily/ubuntu xenial main
/etc/apt/sources.list.d/elementary-os-ubuntu-daily-xenial.list.save:# deb-src http://ppa.launchpad.net/elementary-os/daily/ubuntu xenial main

`sudo ppa-purge ppa:elementary-os/daily`

Then I restarted my laptop.

Maybe it will help somebody.
