### ISSUE TITLE
Remove references to debug flags from man page

### ISSUE THREAD

**Issue by codygarver** [elementary/switchboard#58]
`man switchboard` says `-d` and `--debug` flags exist but this happens:

```
$ switchboard -d
Unknown option -d
```

```
$ switchboard --debug
Unknown option --debug
```

Juno daily `switchboard 2.3.0~r825+pkg54~daily~ubuntu5.0.1`

**Comment by davidmhewitt** [comment]
This will be a side effect of https://github.com/elementary/switchboard/pull/57

As this was something provided by `Granite.Application`, we'll need to add the flags back in manually or forget about them and update the docs.

I'm very much for adding them back in manually as debugging info is useful.

**Comment by tintou** [comment]
They should be removed from the man page.
as said in https://developer.gnome.org/glib/stable/glib-running.html
run `G_MESSAGES_DEBUG=all switchboard` as a replacement to this flag.

**Comment by codygarver** [comment]
Done.
