### ISSUE TITLE
Specify domain name of switchboard and plugs

### ISSUE THREAD

**Issue by tintou** [elementary/switchboard#59]
A recommended GLib way to use and debug applications & plugins is to use logging domain.
We should really start to add the logging domain to switchboard and its plugs.
Two main reasons:
 * You then know where a debug message comes from.
 * You can run `G_MESSAGES_DEBUG=my-log-domain-name switchboard` to only show the wanted debug messages.

How to do it?
Simply add this in the beginning of our files:
```#define G_LOG_DOMAIN "my-log-domain-name"```
```public const string G_LOG_DOMAIN = "my-log-domain-name"```
Or define it project-wide using meson flags.

**Comment by arshubham** [comment]
@tintou I would like to take this up. Any decision been reached over this?

**Comment by danirabbit** [comment]
We already have log domain since #75 it looks like. So just need to add log domains to the individual plugins. Looks like in the panel we do this like:
```
add_project_arguments('-DG_LOG_DOMAIN="io.elementary.wingpanel.power"', language:'c')
```

**Comment by danirabbit** [comment]
Think we got them all :muscle:
