### ISSUE TITLE
Don't prepend ${prefix}/ to @CMAKE_INSTALL_LIBDIR@

### ISSUE THREAD

**Issue by quequotion** [elementary/switchboard#63]
https://github.com/elementary/switchboard/blob/821e70b482a5f6c7c51ba63840ae5246b7dedad5/lib/switchboard.pc.cmake#L3

CMAKE_INSTALL_LIBDIR determines where swtichboard's libraries will be installed, eg if one specifies "-DCMAKE_INSTALL_LIBDIR='/usr/lib'" then libswitchboard-2.0.so will be installed to /usr/lib

There's a problem if one has also specified a prefix, eg if one specifies "-DCMAKE_INSTALL_PREFIX='/usr'" then the pkgconfig will store libdir as /usr//usr/lib, which is then fed to plugsdir, so that subsequent plugs install in /usr/usr/lib/switchboard/(their respective directories).

Noticed this when switchboard plugs stopped appearing in switchboard; similar problem affecting wingpanel's nightlight indicator (not sure where it's getting the install location from, but also in /usr/usr/lib/).

Edit: You might consider it an alternative to not specify DCMAKE_INSTALL_LIBDIR, but this results in switchboard that installs it's libaries to "$prefix/lib64" (or "$prefix/lib32", etc).

**Comment by alucryd** [comment]
Easy fix, --libdir='lib', no leading slash.

**Comment by quequotion** [comment]
Oh, yeah.

I thought I had already tried that, but I must have left the /. I was up pretty late.
