### ISSUE TITLE
Search is disabled from within panels

### ISSUE THREAD

**Issue by alex285** [elementary/switchboard#72]
Reproduce

### 1. Open Settings 
![settings1](https://user-images.githubusercontent.com/11244308/42866123-5d8cf9c4-8a74-11e8-874e-0e44b9e718d6.png)

The focus in on Search Input that is empty, and we can search for settings

### 2. Get inside a panel
![settings2](https://user-images.githubusercontent.com/11244308/42866167-7d58bc98-8a74-11e8-897a-96ea4fd664a5.png)

Now the Search Entry says "Search Settings" but it is disabled

Exactly same issue as in AppCenter https://github.com/elementary/appcenter/issues/743

**Comment by danirabbit** [comment]
I'm going to consider this "fixed" by #239 since we now only show the searchbar on the home page
