### ISSUE TITLE
How would one go about making a switchboard "plug"

### ISSUE THREAD

**Issue by ramirocantu** [elementary/switchboard#73]
There seems to be a lack of available documentation on the topic of third parties making plugs for the switchboard. It is important for third parties to be able to make plugs for the switchboard so that the end user does not clutter their application menu with configuration apps (being those which you generally open one time get your configs down and never touch again).

**Comment by tintou** [comment]
As always, more specific documentation is available in Valadoc.org
https://valadoc.org/switchboard-2.0/Switchboard.Plug.html

But keep in mind that per-application settings shouldn't be there
