### ISSUE TITLE
meson regression: plug directories no longer created

### ISSUE THREAD

**Issue by decathorpe** [elementary/switchboard#78]
There is no equivalent to the current CMake code in meson right now:

```
# Create the standard directories to insert plugs.
install(DIRECTORY DESTINATION ${PLUGS_DIR})
install(DIRECTORY DESTINATION ${PLUGS_DIR}/hardware)
install(DIRECTORY DESTINATION ${PLUGS_DIR}/network)
install(DIRECTORY DESTINATION ${PLUGS_DIR}/personal)
install(DIRECTORY DESTINATION ${PLUGS_DIR}/system)
```

It would be nice if those directories were created by meson during installation, too.

**Comment by decathorpe** [comment]
Will this be reintroduced to meson, or will I have to keep doing this in packaging?

**Comment by danrabbit** [comment]
It looks like dpkg cleans up those directories with the current arrangement, so creating empty directories may be an rpm quirk.

Closing since this isn't required for all packaging systems :)
