### ISSUE TITLE
Untranslated strings

### ISSUE THREAD

**Issue by Djaler** [elementary/switchboard#81]
Looks like it exists in po file, but there are no translation actually.
![image](https://user-images.githubusercontent.com/7964583/44002810-a52eb7d6-9e51-11e8-918b-0f18a08119cb.png)

**Comment by Djaler** [comment]
Upd:
Context menu sections are not translated too
![2018-08-12 17 05 48](https://user-images.githubusercontent.com/7964583/44002841-1c43b8bc-9e52-11e8-849e-d087c456f8a3.png)

**Comment by danrabbit** [comment]
Might be fixed by https://github.com/elementary/switchboard/commit/0fc05c5422c934aab5c83307396a93b6f4cdd77c

**Comment by Djaler** [comment]
Nope :C

**Comment by Djaler** [comment]
Now there are even more untranslated strings, for example, header and sections labels
![image](https://user-images.githubusercontent.com/7964583/44302627-cb0cad80-a335-11e8-87f8-81971aac78dd.png)

**Comment by ryonakano** [comment]
I can confirm this with Switchboard 2.3.3 on Juno Beta2:

![screenshot from 2018-10-06 10-53-50](https://user-images.githubusercontent.com/26003928/46566275-76a9a580-c956-11e8-9b8b-15317bf94083.png)

![2018-10-06 10 54 52](https://user-images.githubusercontent.com/26003928/46566330-4ca4b300-c957-11e8-8ae5-eb2a144dd8e0.png)

![screenshot from 2018-10-06 10-53-52](https://user-images.githubusercontent.com/26003928/46566276-76a9a580-c956-11e8-9ebb-f23415a58a5e.png)

I think we should update translation files again

**Comment by tintou** [comment]
Because the gettext domain wasn't updated internally during the RDNN transition, will be fixed by #89
