### ISSUE TITLE
Compile errors on Rosa Linux

### ISSUE THREAD

**Issue by slava8686** [elementary/switchboard#86]
DEBUG: Install the project...
DEBUG: /usr/bin/cmake -P cmake_install.cmake
DEBUG: -- Install configuration: ""
DEBUG: -- Installing: /builddir/build/BUILDROOT/switchboard-2.3.2-1-rosa2016.1.x86_64-buildroot/usr/share/glib-2.0/schemas/io.elementary.switchboard.gschema.xml
DEBUG: -- Installing: /builddir/build/BUILDROOT/switchboard-2.3.2-1-rosa2016.1.x86_64-buildroot/usr/lib64/switchboard
DEBUG: -- Installing: /builddir/build/BUILDROOT/switchboard-2.3.2-1-rosa2016.1.x86_64-buildroot/usr/lib64/switchboard/hardware
DEBUG: -- Installing: /builddir/build/BUILDROOT/switchboard-2.3.2-1-rosa2016.1.x86_64-buildroot/usr/lib64/switchboard/network
DEBUG: -- Installing: /builddir/build/BUILDROOT/switchboard-2.3.2-1-rosa2016.1.x86_64-buildroot/usr/lib64/switchboard/personal
DEBUG: -- Installing: /builddir/build/BUILDROOT/switchboard-2.3.2-1-rosa2016.1.x86_64-buildroot/usr/lib64/switchboard/system
DEBUG: CMake Error at data/cmake_install.cmake:44 (file):
DEBUG:   file INSTALL cannot find
DEBUG:   "/builddir/build/BUILD/switchboard-2.3.2/build/data/io.elementary.switchboard.desktop".
DEBUG: Call Stack (most recent call first):
DEBUG:   cmake_install.cmake:109 (include)
DEBUG: make: *** [Makefile:87: install] Error 1
DEBUG: make: Leaving directory '/builddir/build/BUILD/switchboard-2.3.2/build'
DEBUG: error: Bad exit status from /var/tmp/rpm-tmp.50420 (%install)

**Comment by tintou** [comment]
Please give more information, we don't know your system, cmake version…

**Comment by slava8686** [comment]
Rosa Linux rpm-base .Cmake 3.7.2

**Comment by slava8686** [comment]
files.spec

Summary:	System Settings
Name:		switchboard	
Version:	2.3.2
Release:	1
License:	LGPLv2+
Group:		Development/Other
Url:		https://elementary.io
Source0:	https://github.com/elementary/switchboard/archive/%{version}.tar.gz?/%{name}-%{version}.tar.gz

BuildRequires:	cmake
BuildRequires:	vala
BuildRequires:	granite-vala
BuildRequires:	pkgconfig(clutter-gtk-1.0)
BuildRequires:	pkgconfig(gee-0.8)
BuildRequires:	pkgconfig(glib-2.0)
BuildRequires:	pkgconfig(granite)
BuildRequires:	pkgconfig(gtk+-3.0)
BuildRequires:	pkgconfig(unity)

%description
Extensible System Settings app designed for elementary OS.

%files -f %{name}.lang

#------------------------------------------------------------------

%prep
%setup -q


%build
%cmake ..
%make

%install
%makeinstall_std -C build

%find_lang %{name}

**Comment by tintou** [comment]
This might be useful https://src.fedoraproject.org/rpms/switchboard/blob/f29/f/switchboard.spec
We don't officially support building on anything else than elementary OS though.

**Comment by slava8686** [comment]
NO...
DEBUG: CMake Error at data/cmake_install.cmake:44 (file):
DEBUG:   file INSTALL cannot find
DEBUG:   "/builddir/build/BUILD/switchboard-2.3.2/build/data/io.elementary.switchboard.desktop".
DEBUG: Call Stack (most recent call first):
DEBUG:   cmake_install.cmake:109 (include)

**Comment by slava8686** [comment]
I don't understand what to do?help please

**Comment by slava8686** [comment]
problem I decided to so
cp -a data/io.elementary.switchboard.desktop.in build/data/io.elementary.switchboard.desktop
cp -a data/io.elementary.switchboard.appdata.xml.in build/data/io.elementary.switchboard.appdata.xml
is it right?

**Comment by slava8686** [comment]
Found, instead of % makeinstall_std -C,  need % make_install

**Comment by danrabbit** [comment]
@slava8686 is this still an issue with the new Meson build system?

**Comment by danrabbit** [comment]
Closing until we hear back from OP :)
