### ISSUE TITLE
Add ability to focus specific setting from search result

### ISSUE THREAD

**Issue by cassidyjames** [elementary/switchboard#88]
Something I've seen in Android is deep-linking to specific settings, like from a search result. In that case, tapping the search result brings you to the proper settings pane but also pre-focuses the specific setting you were looking for.

This is something we could do to make the search from both the app's search bar and the Applications Menu even speedier for keyboard users, plus directly show mouse users where the setting is on the page.

**Comment by peteruithoven** [comment]
It would be great if at the same time could reduce some information duplication. Currently we have:
- `supported_settings` (listing uri's and locations)
- the views / pages themselves (title and location)
- `search` with setting paths, a combination views / pages titles (again) and setting labels, and again locations
- Settings themselves with their labels

It would be great if we could create a system similar to how in word you can create headers of different levels and it can automatically create a table of contents.
So in this case a way to add "path" like info to page titles and individual settings.

**Comment by danrabbit** [comment]
It kind of seems like this could already be done in the `search_callback ()` in each plug. I'm not sure what more Switchboard could do on the library level. This seems like an issue for each individual plug

**Comment by peteruithoven** [comment]
My idea was you create something on the Switchboard level that you can reuse in all the plugs, reducing code duplication and maintaining consistency.

**Comment by danrabbit** [comment]
@peteruithoven I guess I'm not sure how that could be done technically. Given that switchboard doesn't know what is inside plugs, how could the library say which page to switch to and which widget to give focus to?

**Comment by danrabbit** [comment]
I'm gonna close this for Switchboard because I don't think it's possible to do it from Switchboard's side. If we'd like to do this it has to be implemented in each plug
