### ISSUE TITLE
Password visible in Authentication Required dialog

### ISSUE THREAD

**Issue by satran** [elementary/switchboard#91]
This happens when I have enabled `pam_fprintd.so` in pam config. When unlocking a system setting for administrative rights if the fingerprint reader is ready for scanning typing my password is visible in plain text. Here is a screenshot of it:

![screenshot from 2018-10-21 21 49 11](https://user-images.githubusercontent.com/437678/47271609-4e878c80-d57b-11e8-9dee-d8bbdd6ce3a7.png)

**Comment by danrabbit** [comment]
These authentication dialogs come from a different component than Switchboard. Closing this report as "Out of scope" since this is a bug with a different component.

You can open a new issue against the Polkit Agent here: https://github.com/elementary/pantheon-agent-polkit/issues
