### ISSUE TITLE
header flat view

### ISSUE THREAD

**Issue by torikulhabib** [elementary/switchboard#92]
how about with header flat.
i think make appearance simple.
![screenshot from 2018-10-28 16 36 47](https://user-images.githubusercontent.com/26135527/47614345-3a8ae000-dad1-11e8-944e-eb3b928f4ef6.png)

**Comment by cassidyjames** [comment]
In elementary OS, the flat/dialog style has very specific meaning: it signifies that the window is transient and lightweight; that is, it will not require much interaction and it is temporary. That's very much not the case with System Settings, as there are nearly two dozen different plugs, each with their own internals, many of which with their own tabs or sections. It is anything but transient.
